# Generated by Django 3.2.22 on 2023-10-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_rename_choice_text_choice_choice1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice1',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='yes', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text1',
            field=models.CharField(default='no', max_length=200),
        ),
    ]
