# Generated by Django 3.2.22 on 2023-10-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20231012_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text1',
        ),
    ]
