# Generated by Django 3.2.22 on 2023-10-15 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_remove_choice_choice_text1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 13, 35, 2, 73477, tzinfo=utc), verbose_name='date published'),
        ),
    ]
