# Generated by Django 3.2.22 on 2023-10-17 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20231017_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 15, 47, 48, 411885, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(default='12', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.group'),
        ),
    ]
