# Generated by Django 3.2.22 on 2023-10-17 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20231017_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 15, 49, 2, 394817, tzinfo=utc), verbose_name='date published'),
        ),
    ]
