# Generated by Django 3.2.22 on 2023-10-17 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_alter_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 15, 52, 6, 75757, tzinfo=utc), verbose_name='date published'),
        ),
    ]
