# Generated by Django 3.2.22 on 2023-10-17 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20231017_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(default='12', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.group'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 15, 52, 37, 619587, tzinfo=utc), verbose_name='date published'),
        ),
    ]
