# Generated by Django 3.2.22 on 2023-10-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20231019_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '精细动作能力水平'), (2, '情绪、社会能力开展水平'), (3, '精细动作能力水平'), (4, '认知能力开展水平'), (5, '语言能力开展水平')], default=1),
        ),
    ]
