# Generated by Django 3.2.22 on 2023-10-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20231019_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.IntegerField(default=12),
        ),
    ]
