# Generated by Django 3.2.22 on 2023-10-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20231019_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[(1, '家长题目'), (2, '操作题目'), (3, '运动题目')], default=2, max_length=200),
            preserve_default=False,
        ),
    ]
