# Generated by Django 3.2.22 on 2023-10-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_alter_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.IntegerField(choices=[(1, '家长题目'), (2, '操作题目'), (3, '运动题目')], default=1),
        ),
    ]
