# Generated by Django 3.2.22 on 2023-10-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_auto_20231019_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.IntegerField(default=12),
        ),
    ]
