# Generated by Django 3.2.22 on 2023-10-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '精细动作能力水平'), (2, '情绪、社会能力开展水平'), (3, '精细动作能力水平'), (4, '认知能力开展水平'), (5, '语言能力开展水平'), (6, '大动作能力水平')], default=1),
        ),
    ]
