# Generated by Django 3.2.22 on 2023-10-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0019_userresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
