# Generated by Django 3.2.22 on 2023-10-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0021_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'Normal User'), ('staff', 'Staff')], default='user', max_length=20),
        ),
    ]
