# Generated by Django 3.2.22 on 2023-10-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0022_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='templates/question_pictures')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '精细动作能力水平'), (2, '情绪、社会能力开展水平'), (3, '精细动作能力水平'), (4, '认知能力开展水平'), (5, '语言能力开展水平'), (6, '大动作能力水平'), (7, '粗大运动-姿势'), (8, '粗大运动-移动'), (9, '粗大运动-实物操作'), (10, '精细运动-抓握'), (11, '精细运动-视觉-运动整合')], default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.picture'),
        ),
    ]
