# Generated by Django 3.2.22 on 2023-10-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0023_auto_20231030_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='posture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='stimulus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
