# Generated by Django 3.2.22 on 2023-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0024_auto_20231030_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='operation_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
