# Generated by Django 3.2.22 on 2023-11-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0025_question_operation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='operation_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='question',
            name='posture',
        ),
        migrations.RemoveField(
            model_name='question',
            name='stimulus',
        ),
        migrations.RemoveField(
            model_name='question',
            name='task',
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.IntegerField(choices=[(1, '家长题目'), (2, '操作题目')], default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '精细动作能力水平'), (2, '情绪、社会能力开展水平'), (3, '精细动作能力水平'), (4, '认知能力开展水平'), (5, '语言能力开展水平'), (6, '大动作能力水平')], default=1),
        ),
        migrations.CreateModel(
            name='OperationQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, '粗大运动-姿势'), (2, '粗大运动-移动'), (3, '粗大运动-实物操作'), (4, '精细运动-抓握'), (5, '精细运动-视觉-运动整合')], default=1)),
                ('task', models.TextField(blank=True, null=True)),
                ('stimulus', models.TextField(blank=True, null=True)),
                ('posture', models.TextField(blank=True, null=True)),
                ('operation_id', models.IntegerField(blank=True, default=-1, null=True)),
                ('group', models.ForeignKey(default='12', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.group')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.picture')),
            ],
        ),
    ]
