# Generated by Django 3.2.22 on 2023-11-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0026_auto_20231101_1423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperationQuestions',
            new_name='OperationQuestion',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='operation_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.operationquestion'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question'),
        ),
    ]
