# Generated by Django 3.2.22 on 2023-11-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0027_auto_20231101_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
