# Generated by Django 3.2.22 on 2023-11-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0029_auto_20231102_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='operation_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
