# Generated by Django 3.2.22 on 2023-11-14 14:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0030_userresponse_operation_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='operation_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
