# Generated by Django 3.2.22 on 2023-11-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0031_alter_userresponse_operation_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='operation_points',
        ),
        migrations.CreateModel(
            name='UserOperationPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '粗大运动-姿势'), (2, '粗大运动-移动'), (3, '粗大运动-实物操作'), (4, '精细运动-抓握'), (5, '精细运动-视觉-运动整合')], default=1)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.userprofile')),
            ],
        ),
    ]
