# Generated by Django 3.2.22 on 2023-11-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0032_auto_20231115_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useroperationpoints',
            old_name='points',
            new_name='operation_points',
        ),
    ]
