# Generated by Django 3.2.22 on 2023-11-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0033_rename_points_useroperationpoints_operation_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='answer_time',
            field=models.IntegerField(blank=True, choices=[(1, '粗大运动-姿势'), (2, '粗大运动-移动'), (3, '粗大运动-实物操作'), (4, '精细运动-抓握'), (5, '精细运动-视觉-运动整合')], default=-1, null=True),
        ),
    ]
