# Generated by Django 4.2.7 on 2023-11-29 15:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0035_useroperationpoints_answer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroperationpoints',
            name='points_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
