# Generated by Django 4.2.7 on 2023-11-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0036_useroperationpoints_points_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroperationpoints',
            name='points_list',
        ),
    ]
