# Generated by Django 4.2.7 on 2023-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0037_remove_useroperationpoints_points_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
