# Generated by Django 4.2.7 on 2023-12-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0039_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hospital',
            field=models.IntegerField(choices=[(0, '上海中易'), (1, '上海市妇幼中心'), (2, '奉贤区妇幼中心')], default=0),
        ),
    ]
